# Generated by Django 5.0.6 on 2024-06-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels_web', '0003_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotels\\Hotels_web\\static\\hotels\\images'),
        ),
    ]
