# Generated by Django 5.0.6 on 2024-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels_web', '0005_alter_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=-1, upload_to='hotels\\images'),
            preserve_default=False,
        ),
    ]
